baseURL = "https://pedantic-ardinghelli-7de9dc.netlify.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Sam Castle"
theme = "cupper-hugo-theme"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "I'm a software engineer interested in learning, entrepreneurship, reading, and the outdoors."
  homeMetaContent = "Sam Castle is a software engineer interested in learning, entrepreneurship, reading, and the outdoors."
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = true

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Blog"
    url = "/post/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 4
